### ISSUE TITLE
mk_prepare_receptor in autodock vina basic docking colab example? 

### ISSUE THREAD

**Issue by 42DegNorth** [forlilab/Meeko#205] opened 2024-10-18 16:56 UTC
Hi, all: 
I am experimenting my first docking following the basic docking colab example but having issue with meeko mk_prepare_receptor command when prepare the receptor

https://autodock-vina.readthedocs.io/en/latest/colab_examples.html

first I have to change 
! git clone --single-branch --branch cli_flags_output_design https://github.com/forlilab/Meeko.git
! cd Meeko; pip install --use-pep517 -e .; cd ..

to use release branch as the cli_flags_output_design branch does not exist anymore (not too sure about the --use-pre517 parameter so I kept it) 
! git clone --single-branch --branch release https://github.com/forlilab/Meeko.git
! cd Meeko; pip install --use-pep517 -e .; cd ..

second 
have to change this command 
! python {mk_prepare_receptor} -i {prepare_inPDB} -o {prepare_output} -p -v --box_center {center_x} {center_y} {center_z} --box_size {size_x} {size_y} {size_z}

to the following too (guess the parameter for the new version are changed) 

! python {mk_prepare_receptor} --pdb {prepare_inPDB} -o {prepare_output} --box_center {center_x} {center_y} {center_z} --box_size {size_x} {size_y} {size_z}

And then I am getting the following error with 1iep and tried other proteins too same error. 

did not match ('A', 'HIS', 246) with template
did not match ('A', 'HIS', 295) with template
did not match ('A', 'HIS', 361) with template
did not match ('A', 'HIS', 375) with template
did not match ('A', 'HIS', 396) with template
did not match ('A', 'HIS', 490) with template
Error: residue HIS not in residue_params
residue HIS not in residue_params
residue HIS not in residue_params
residue HIS not in residue_params
residue HIS not in residue_params
residue HIS not in residue_params

What did I do wrong? if not using mk_prepare_receptor I saw there is a prepare_receptor we can use but what package I need to install and how?  Very new to autodock. 

Thanks in advance for any help/tips.

**Comment by rwxayheee** [comment] 2024-10-18 17:14
Hello @42DegNorth 
I wrote the notebooks, and I left the temporary branch name there for #194 before it was merged (days ago) as there were some major syntax changes. Sorry for the confusion. 

The correct branch to checkout is `develop`. I will update the notebooks a little later today. Some of them still need the fixes to be up-to-date with the recent changes. We have an open issue here (#192)

`release` is outdated for the notebooks. 

Please feel free to comment here for any questions, comments, and suggestions you may have regarding this. If you need help with a specific system and you're able to share them, please post the file we can take a look and happy to help! 


I fixed and regenerated the outputs for the first example: 
https://colab.research.google.com/drive/1cHSl78lBPUc_J1IZxLgN4GwD_ADmohVU?usp=sharing

The other two need a little bit more work. I will come back to them a little later today. Thanks again for bringing this to our attention

**Comment by rwxayheee** [comment] 2024-10-18 18:21
Hi, I updated all three examples we posted on Vina Read The Doc. They should be working with the current develop branch now ^^ , 
If you have any comments / suggestions, feel free to reopen this or another issue for specific questions

**Closed as completed by rwxayheee** 2024-10-18 18:21 UTC

**Comment by 42DegNorth** [comment] 2024-10-18 18:30
Wow, I did not expect this kind quick response. 👍 thank you so much!
I will give it a try. 

Another question I have is (you probably can tell already that I am not a biology major) 
When we prepare the receptor you select the ligand (due to the Prody selection language is "chain A and resname STI") in this case "STI" to calc the center of the docking. Is this assume the protain must contain STI? This is confusing to me (because we are trying to see how ligand STI docks on protein 1iep, correct? Or I totally understand it wrong? Can the mk_prepare_receptor work without providing the docking center of the ligand? understandably it probably much slower.  

What I am trying to achieve is I have about 1k ligands and want to get their docking score on certain protein and then do some analysis. 

Again,thank you

**Comment by rwxayheee** [comment] 2024-10-18 18:48
Hi @42DegNorth 

> When we prepare the receptor you select the ligand (due to the Prody selection language is "chain A and resname STI") in this case "STI" to calc the center of the docking. Is this assume the protain must contain STI? 

In this example, yes. STI is the residue name of the ligand in the input PDB structure ([PDB ID 1IEP](https://www1.rcsb.org/structure/1IEP)). The ligand name is searchable on PDB too: https://www1.rcsb.org/ligand/STI

In Step 1.2(2) of this example: 
```
Use ProDy selection language to specify (ligand, residue, or any) atoms for box center calculation. In this example, we choose the ligand and will use the geometric center of ligand as box center.
```
I took the ligand part of the PDB structure to define the center of the box, because the input structure contains the ligand. In practice, you can set the center of the box in many different ways: 
- change the `ligand_selection` to a selection of binding site residue(s), 
- change the `ligand_selection` to a specific atom, 
- set the center of box directly by X Y Z coordinates, etc.

> Can the mk_prepare_receptor work without providing the docking center of the ligand? understandably it probably much slower. 

Currently, mk_prepare_receptor requires the definition of the box (center & size) when you ask for a vina box file (-v) or grid file (-g). For basic docking, there are two combinations: 
(a) --box_size and --box_center
(b) --box_enveloping and --padding (you could see it in the other example: https://colab.research.google.com/drive/1cazEckGbvl9huWzpxXpd_Qaj0_NipWcz?usp=sharing#scrollTo=tpzIFKjyu44k), which set up the box so that it wraps the object (--box_enveloping) with a padding distance in each dimension (--padding)

If you only want a .PDBQT (-p) and/or .JSON (-j) file from mk_prepare_receptor, the definition of he box is not required. 

The time needed for docking calculation (and reproducibility of the docking calculation) depends more on the size of the box. 

Hope this helps!
